{{- if and .Values.mistral.enabled (not .Values.mistral.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextcloud-mcp-server.fullname" . }}-mistral
  labels:
    {{- include "nextcloud-mcp-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.mistral.secretKey }}: {{ .Values.mistral.apiKey | b64enc | quote }}
{{- end }}
